///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Things to do only once - Borrowed and modified from SCS               //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
ACTION_IF !VARIABLE_IS_SET ~initialise~ BEGIN

  ACTION_IF ((FILE_EXISTS ~dlc/sod-dlc.zip~) OR (FILE_EXISTS ~sod-dlc.zip~)) THEN BEGIN FAIL @3001 END // Modmerge check

  CLEAR_EVERYTHING            // occasionally, e.g. after installing IWD spells, we call this again. Make sure we get a fresh start.
  //SILENT
  OUTER_SET initialise=1

///////////////////////////////////////////////////////////////////////////
// Set up ini system                                                     //
///////////////////////////////////////////////////////////////////////////
   INCLUDE ~forgotten-armament/lib/lib_ini.tpa~
    OUTER_SPRINT ini_to_read "forgotten-armament/forgotten-armament.ini"
    LAF SFO_read_ini_file RET_ARRAY SFO_reserved_ini_hash END

///////////////////////////////////////////////////////////////////////////
// General variables, macros and functions                               //
///////////////////////////////////////////////////////////////////////////
   INCLUDE ~forgotten-armament/sfo/install_sfo.tpa~
   INCLUDE ~forgotten-armament/lib/lib.tpa~
   INCLUDE ~forgotten-armament/lib/macros.tpa~
   OUTER_SPRINT ~folder~ ~forgotten-armament~
   //SILENT

///////////////////////////////////////////////////////////////////////////
// Detect third-party mods                                               //
///////////////////////////////////////////////////////////////////////////
   // Detect Rogue Rebalancing
   ACTION_IF MOD_IS_INSTALLED ~setup-rr.tp2~ ~7~ THEN BEGIN
      OUTER_SET rogue_rebalancing=0
   END ELSE BEGIN
      OUTER_SET rogue_rebalancing=1
   END

END
